name: storeload
description: An e-commerce app

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  # State management
  stacked: ^3.2.7
  stacked_services: ^1.0.2
  # Network
  dio: ^5.0.1
  dartz: ^0.10.1
  connectivity_plus: ^3.0.3
  # Model
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

   #Hive Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.11.0
  flutter_screenutil: ^5.8.1
  flutter_svg: ^2.0.3
  otp_text_field: ^1.1.3
  otp_timer_button: ^1.1.0
  logger: ^1.3.0
  flutter_overlay_loader: ^2.0.0
  animations: ^2.0.7
  intl:
  grouped_list: ^5.1.2
  shared_preferences: ^2.1.1
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.4.0

 
  
dev_dependencies:
  build_runner: ^2.3.3
  stacked_generator: ^1.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0

  flutter_test:
    sdk: flutter
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_logo.png"

  
flutter:
   uses-material-design: true
   fonts:
    - family: ClashGrotesk
      fonts:
      - asset: fonts/ClashGrotesk-Medium.otf
        weight: 500
    - family: Amulya
      fonts:
      - asset:  fonts/Amulya-Regular.otf
        weight: 400
      - asset: fonts/Amulya-Medium.otf
        weight: 500
   assets:
    - assets/icons/
    - assets/images/
    - assets/images/product_thumbnail/

  

  
